/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.GenericDao;
import java.awt.event.KeyEvent;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import tabelas.Mensagens;
import tabelas.Usuarios;

/**
 *
 * @author CEDUP TIMBO
 */
public class jfMensagens extends javax.swing.JFrame {
    int codigo_usuarios;
    String chat = "";
    int codigo_salas;
    String usuario;
    int sair = 0;
    
    
    

    /**
     * Creates new form jfMensagens
     */
    public jfMensagens() {
        initComponents();
    }
    public jfMensagens(int user, int sala) {
        initComponents();
        codigo_usuarios = user;
        codigo_salas = sala;
        try {
            GenericDao g = new GenericDao();
            List<Object> lista = g.listar(Usuarios.class);
             for(Object l : lista){
                Usuarios u = (Usuarios) l;
                if(u.getCodigo_usuarios()==codigo_usuarios){
                    usuario = u.getApelido_usuarios();
                    
                }
            Thread p = new Thread(new Processo(), "Atualizar");
            p.start();
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAsala = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLsala = new javax.swing.JLabel();
        jTFmensagem = new javax.swing.JTextField();
        jLstatus = new javax.swing.JLabel();
        jLicon = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAsala.setEditable(false);
        jTAsala.setColumns(20);
        jTAsala.setRows(5);
        jScrollPane1.setViewportView(jTAsala);

        jButton1.setText("Emotion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLsala.setBackground(new java.awt.Color(0, 0, 0));
        jLsala.setText("  SALA  ");
        jLsala.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 204)));
        jLsala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTFmensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFmensagemKeyPressed(evt);
            }
        });

        jLstatus.setText("0");

        jLicon.setText("icon");

        jLusuario.setText("usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFmensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLicon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLusuario))
                            .addComponent(jLsala))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLsala, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLstatus)
                        .addComponent(jLicon)
                        .addComponent(jLusuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFmensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFmensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            Calendar c = Calendar.getInstance();
            System.out.println(c.get(Calendar.DATE));
            System.out.println(c.get(Calendar.DAY_OF_MONTH)+"/"+((c.get(Calendar.MONTH))+1)+"/"+c.get(Calendar.YEAR));
            System.out.println(""+c.get(Calendar.HOUR_OF_DAY)+":"+c.get(Calendar.MINUTE));
            
            
            try {
                GenericDao gd = new GenericDao();
                Mensagens m = new Mensagens();
                m.setmensagens(jTFmensagem.getText());
                m.setCodigo_salas(codigo_salas);
                m.setCodigo_usuarios_destino(codigo_salas);
                m.setCodigo_usuarios_origem(codigo_usuarios);
                m.setData_envio_mensagens(c.get(Calendar.DAY_OF_MONTH)+"/"+((c.get(Calendar.MONTH))+1)+"/"+c.get(Calendar.YEAR));
                m.setHora_envio_mensagens(""+c.get(Calendar.HOUR_OF_DAY)+":"+c.get(Calendar.MINUTE));
                gd.adicionar(m);
            } catch (SQLException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            }
            /*chat = chat+"\r\n"+usuario+" : "+jTFmensagem.getText();
            jTAsala.setText(chat);
            jTFmensagem.setText("");
            jLusuario.setText(usuario);*/
        }
    }//GEN-LAST:event_jTFmensagemKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMensagens().setVisible(true);
            }
        });
    }
     public class Processo implements Runnable {

        @Override
        public void run() {
            try {
                GenericDao gd = new GenericDao();
                while(sair==0){
                    Thread.sleep(1000);
                    List<Object> lista = gd.listar(Mensagens.class);
                    String chat = "";
                    for(Object l : lista){
                        Mensagens m = (Mensagens) l;
                        if(m.getCodigo_salas()==codigo_salas){
                            chat = chat+m.getData_envio_mensagens();
                            chat = chat+"\r\n"+m.getmensagens();
                        }
                    }
                    jTAsala.setText(chat);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchMethodException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvocationTargetException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(jfMensagens.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
                            
                                
                            
                    
                
        }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLicon;
    private javax.swing.JLabel jLsala;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTAsala;
    private javax.swing.JTextField jTFmensagem;
    // End of variables declaration//GEN-END:variables
}
